version: '3,7'
volumes:
  volMysql:
services:
  dbMysql:
    image: mysql:latest
    container_name: 'mysqlcontainer'
    environment:
      - MYSQL_ROOT_PASSWORD=bdSecret
      - MYSQL_DATABASE=storeadvance
    ports:
      - 3307:3306
    volumes:
      - volMysql:/var/lib/mysql
